In [2]:
import numpy as np

In [3]:
arr = np.arange(11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [3]:
A = np.random.randn(10)

A

array([ 0.39394705,  0.71912787, -0.82650593,  0.81530866,  1.62532313,
        0.5712988 ,  0.25003493, -2.43146381,  0.65339068, -0.1488843 ])

In [5]:
B = np.random.randn(10)
B

array([ 0.5224646 , -1.75291229, -0.37953555,  0.75313026,  0.22719286,
        1.60123726,  0.80405996, -0.03571908, -0.60184508, -1.69128025])

In [6]:
# Binary Functions
np.add(A,B)

array([ 0.91641165, -1.03378442, -1.20604148,  1.56843892,  1.85251599,
        2.17253606,  1.05409489, -2.46718289,  0.05154559, -1.84016455])

In [8]:
np.maximum(A,B)

array([ 0.5224646 ,  0.71912787, -0.37953555,  0.81530866,  1.62532313,
        1.60123726,  0.80405996, -0.03571908,  0.65339068, -0.1488843 ])

In [9]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)


True